# Generated by Django 4.0.2 on 2022-02-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='tag-django', max_length=31, unique=True),
        ),
    ]
