# Generated by Django 3.2.9 on 2022-02-13 06:03

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_tag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=31)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=31, populate_from=['name'], unique=True)),
                ('description', models.TextField()),
                ('date_founded', models.DateField(auto_now_add=True)),
                ('contact', models.EmailField(max_length=254)),
                ('tags', models.ManyToManyField(to='organizer.Tag')),
            ],
            options={
                'get_latest_by': ['date_founded'],
            },
        ),
    ]
